### ISSUE TITLE
Normalizing the Locality model

### ISSUE THREAD

**Issue by gcrsaldanha** [gems-uff/labsys#4]
@leomurta 
I have a Locality class with Country, State, City, Neighborhood, Zone. It's being used as Patient's "address"  attribute.

I also have the AdmissionNote class which has "health_unit" as a string attribute, plus "state" and "city" attributes (which refer to the health unit which this admission note belongs to).

Should I encapsulate state and city as "Locality" even though it only uses state and city, creating a foreign key to Locality in Admission Note?

**Comment by leomurta** [comment]
What about talking about this tomorrow, at the group meeting?

**Comment by gcrsaldanha** [comment]
Solution: split HealthUnit from AdmissionNote and City/State/Country from Locality.
